
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT  = 'LOGOUT';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const ACTOR_TYPE_CHANGE = 'ACTOR_TYPE_CHANGE';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const FETCH_TRIP_START = 'FETCH_TRIP_START';
export const FETCH_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const FETCH_TRIP_FAIL = 'FETCH_TRIP_FAIL';

export const CANCEL_TRIP = 'CANCEL_TRIP';

export const SEND_ORDER = 'SEND_ORDER';

export const SOCKET_ERROR = 'SOCKET_ERROR';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_CLOSED = 'SOCKET_CLOSED';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
